### ISSUE TITLE
/proc must be mount error after using service idena start/stop

### ISSUE THREAD

**Issue by shaunakbale** [ltraveler/idena-armer#1]
Whenever I try to run service idena start/stop command I am encountering with /proc must be mount error which causes idena node neither to start or stop, i am assuming this due to android policies, I am currently on Android 12

![Screenshot 2022-10-08 at 23-32-00 (1) WhatsApp](https://user-images.githubusercontent.com/94175476/194721256-85cd0f46-564d-4d62-8488-6ae4c2405262.png)

**Comment by ltraveler** [comment]
This issue is related to Android 8 or above. The solution will be ready in a couple of days.

**Comment by ltraveler** [comment]
The problem has been fixed.
Please remove Kali Linux and follow the further steps as it is described here:
https://medium.com/@idna.project/b9229c010440/#cde3
